### ISSUE TITLE
cookie配置后docker无法启动

### ISSUE THREAD

**Issue by zqz981** [gochendong/suno-api#3]
错误反馈：
2024-11-22 16:46:21 suno-api  |   File "/app/main.py", line 5, in <module>
2024-11-22 16:46:21 suno-api  |     from deps import get_token
2024-11-22 16:46:21 suno-api  |   File "/app/deps.py", line 1, in <module>
2024-11-22 16:46:21 suno-api  |     from cookie import suno_auth, keep_alive
2024-11-22 16:46:21 suno-api  |   File "/app/cookie.py", line 79, in <module>
2024-11-22 16:46:21 suno-api  |     fetch_session_id(suno_auth)
2024-11-22 16:46:21 suno-api  |   File "/app/cookie.py", line 62, in fetch_session_id
2024-11-22 16:46:21 suno-api  |     expire_at = resp.json().get("response").get("sessions")[0]["expire_at"]
2024-11-22 16:46:21 suno-api  | IndexError: list index out of range

**Comment by gochendong** [comment]
那应该是cookie取错了 取cookie的接口名是啥

**Comment by zqz981** [comment]
一种是通过 网络流量摘取的，我的样例如下(部分字段的内容用xxx替代了)：
__client_uat=xxxx; ajs_anonymous_id=xxxx-xxxx-47f1-8cef-c1a40c83b78e; __client_uat_U9tcbTPE=1732257019; _ga_7B0KEDD7XP=GS1.1.1732265368.2.1.1732266068.0.0.0; _ga=GA1.1.783930771.1732256998; __session_U9tcbTPE=eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDExMUFBQSIsImtpZCI6Imluc18yT1o2eU1EZzhscWRKRWloMXJvemY4T3ptZG4iLCJ0eXAiOiJKV1QifQ.eyJhdWQiOiJzdW5vLWFwaSIsImF6cCI6Imh0dHBzOi8vc3Vuby5jb20iLCJleHAiOjE3MzIyNjYxMjcsImZ2YSI6WzE1MCwtMV0sImh0dHBzOi8vc3Vuby5haS9jbGFpbXMvY2xlcmtfaWQiOiJ1c2VyXzJlaTJjQ1BKbXdocnFLZWQ4OVRhYkkxWnpUTiIsImh0dHBzOi8vc3Vuby5haS9jbGFpbXMvZW1haWwiOiJ6cXo5ODFAZ21haWwuY29tIiwiaHR0cHM6Ly9zdW5vLmFpL2NsYWltcy9waG9uZSI6bnVsbCwiaWF0IjoxNzMyMjY2MDY3LCJpc3MiOiJodHRwczovL2NsZXJrLnN1bm8uY29tIiwianRpIjoiYzE2NTVmZTJlNmQxZDFjZDc3YWYiLCJuYmYiOjE3MzIyNjYwNTcsInNpZCI6InNlc3NfMnBDNTNuMFEwSTdMWUJHMUxvTFU3aEZZOTNQIiwic3ViIjoidXNlcl8yZWkyY0NQSm13aHJxS2VkODlUYWJJMVp6VE4ifQ.Yw7GnZUuvq63zBGK-NEeUr88_xBmKgnbqqrSbvvd5SUE61qDRRaYKcwJg07_6Tqj8365zf-RKK6eIx-JG50O2jPO2QLryf9QSAVDcI4mZP0RCv0kl4d3kHZRqtAzneF0Q6XjGy0xuT12TQbooXWCiZxz1uKj3IShh9lZR8RnPkkLBQ9na-wC8_GJmCcT5EksVqiwXcitcksmq35s5D6S6kGSzHrD_MDVexxxRiVtVAuVZkWmio7z0mhEl1D4OeHpOfR7AQNczwQ2BG1-imBP2aFPadT_8Wp7DU6mfrx-cLbwu8NipSDS63Qwcrq8JBnqwaFGuxgiFCw-JxGhJg; __refresh_U9tcbTPE=FYMGJgVbGcqs23zAJEoO; __session=eyJhbGciOxxxxhdCI6ImNsX0I3ZDRQRDExMUFBQSIsImtpZCI6Imluc18yT1o2eU1EZzhscWRKRWloMXJvemY4T3ptZG4iLCJ0eXAiOiJKV1QifQ.eyJhdWQiOiJzdW5vLWFwaSIsImF6cCI6Imh0dHBzOi8vc3Vuby5jb20iLCJleHAiOjE3MzIyNjYxMjcsImZ2YSI6WzE1MCwtMV0sImh0dHBzOi8vc3Vuby5haS9jbGFpbXMvY2xlcmtfaWQiOiJ1c2VyXzJlaTJjQ1BKbXdocnFLZWQ4OVRhYkkxWnpUTiIsImh0dHBzOi8vc3Vuby5haS9jbGFpbXMvZW1haWwiOiJ6cXo5ODFAZ21haWwuY29tIiwiaHR0cHM6Ly9zdW5vLmFpL2NsYWltcy9waG9uZSI6bnVsbCwiaWF0IjoxNzMyMjY2MDY3LCJpc3MiOiJodHRwczovL2NsZXJrLnN1bm8uY29tIiwianRpIjoiYzE2NTVmZTJlNmQxZDFjZDc3YWYiLCJuYmYiOjE3MzIyNjYwNTcsInNpZCI6InNlc3NfMnBDNTNuMFEwSTdMWUJHMUxvTFU3aEZZOTNQIiwic3ViIjoidXNlcl8yZWkyY0NQSm13aHJxS2VkODlUYWJJMVp6VE4ifQ.Yw7GnZUuvq63zBGK-NEeUr88_xBmKgnbqqrSbvvd5SUE61qDRRaYKcwJg07_6Tqj8365zf-RKK6eIx-JG50O2jPO2QLryf9QSAVDcI4mZP0RCv0kl4d3kHZRqtAzneF0Q6XjGy0xuT12TQbooXWCiZxz1uKj3IShh9lZR8RnPkkLBQ9na-wC8_GJmCcT5EksVqiwXcitcksmq35s5D6S6kGSzHrD_MDVeD5dHsavRiVtVAuVZkWmio7z0mhEl1D4OeHpOfR7AQNczwQ2BG1-imBP2aFPadT_8Wp7DU6mfrx-cLbwu8NipSDS63Qwcrq8JBnqwaFGuxgiFCw-JxGhJg; __stripe_mid=9421205c-d14a-4415-b170-6388ddad1e175bfd98; mp_26ced217328f4737497bd6ba6641ca1c_mixpanel=%7B%22distinct_id%22%3A%20%22e5daa6c2-1794-4b65-afb2-ed4a268cbfac%22%2C%22%24device_id%22%3A%20%221907bf3368e3533-0f3c1b2f4573c-e525627-bdd80-1907bf3368f3534%22%2C%22%24initial_referrer%22%3A%20%22%24direct%22%2C%22%24initial_referring_domain%22%3A%20%22%24direct%22%2C%22__mps%22%3A%20%7B%7D%2C%22__mpso%22%3A%20%7B%7D%2C%22__mpus%22%3A%20%7B%7D%2C%22__mpa%22%3A%20%7B%7D%2C%22__mpu%22%3A%20%7B%7D%2C%22__mpr%22%3A%20%5B%5D%2C%22__mpap%22%3A%20%5B%5D%2C%22%24user_id%22%3A%20%22e5daa6c2-1794-4b65-afb2-ed4a268cbfac%22%7D

**Comment by gochendong** [comment]
接口是哪一个 ？应该是client关键字的接口 用chrome浏览器

**Comment by zqz981** [comment]
你说的是抓取的交互信息里面的url吗？
https://clerk.suno.com/v1/client?__clerk_api_version=2021-02-05&_clerk_js_version=5.34.4
这个接口，我重新复制了一份这个接口的cookie，并重新build了一下。 现在好了。 可以用啦。
谢谢提醒！
