### ISSUE TITLE
what is the cookie expiration date?

### ISSUE THREAD

**Issue by 2easyjunmin** [gochendong/suno-api#8]
I have two questions.

How often should I perform manual generation on webpages?
Also, what is the cookie expiration date?

**Comment by gochendong** [comment]
about 6 hours 

cookie will expire in 90days

**Comment by 2easyjunmin** [comment]
Is there any way to automate this? @gochendong

**Comment by gochendong** [comment]
difficult to automate that. try to use multi accounts to keep service continuous

**Comment by 2easyjunmin** [comment]
thanks for your opinion!!!!

**Comment by 2easyjunmin** [comment]
You have to make manual requests on the web anyway,
and need to renew once every 90 days, why create multiple accounts?
Because manual request and renewal is mandatory whether you have one account or multiple.

If this is a workflow I haven't thought of, I'd really appreciate it if you could explain it!
@gochendong

**Comment by gochendong** [comment]
Manual requests can achieve several hours of availability. We can stagger the time points for manual requests for each account to maintain overall service availability. @2easyjunmin

**Comment by 2easyjunmin** [comment]
Is it correct that CAPTCHA availability is approximately 6 hours? Because there was talk of 2 hours. I want to know for sure and set up!
Sorry for all the questions :)

**Comment by 2easyjunmin** [comment]
Is it correct that CAPTCHA availability is approximately 6 hours? Because there was talk of 2 hours. I want to know for sure and set up!

And can you explain a little bit more about staggering manual requests?
For example, I have one account and I need to make a manual request every 5 hours.
is it still the same for multiple accounts to have a manual request every 5 hours?

Because 5 hours is the same for all accounts anyway.
And even if you don't manually request at the same time, but stagger it.
Doesn't the fact that I deviate from manual requests mean that I have to do it every 5 hours?

Sorry for all the questions :) @gochendong

**Comment by gochendong** [comment]
@2easyjunmin 
<img width="388" alt="image" src="https://github.com/user-attachments/assets/1cef5ab2-3301-49b6-8e4f-a8014325690b">
Yes, it takes about 6 to 8 hours. You have to manually create a song, and you may encounter complex graphic verification.

**Comment by gochendong** [comment]
@2easyjunmin 
<img width="798" alt="image" src="https://github.com/user-attachments/assets/f6fdabb4-1896-4310-9cc5-48a368b09d1c"> 
This is my detection program, once every hour. Green represents correct.

**Comment by 2easyjunmin** [comment]
So whether you're using one account or multiple, you're probably making a manual request at least once every five hours.
Thanks! @gochendong

**Comment by CalvinChenXYZ** [comment]
> @2easyjunmin <img alt="image" width="798" src="https://private-user-images.githubusercontent.com/39932550/389758151-f6fdabb4-1896-4310-9cc5-48a368b09d1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwMTYzNzMsIm5iZiI6MTczMzAxNjA3MywicGF0aCI6Ii8zOTkzMjU1MC8zODk3NTgxNTEtZjZmZGFiYjQtMTg5Ni00MzEwLTljYzUtNDhhMzY4YjA5ZDFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAxVDAxMjExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1ZWVhNDc3YTRhZjE4OTFjMjMzY2Q2ZjRlZDkwOTAyYTJmMjliM2NlOTUwODEzMDEyNDA0MDdiN2E1ZDA3NDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xQSdCwxKBHD0cnCZMMauTVGNmDZ2k_y207NgLtjWhvM"> This is my detection program, once every hour. Green represents correct.

Thank you so much for your amazing work! We truly appreciate your contributions. Would you consider setting up a Buy Me a Coffee profile so we can buy you some coffees as well? We’ve already supported gcui’s profile https://buymeacoffee.com/gcui and would love to do the same for you as a small token of our gratitude. ❤️

**Comment by gochendong** [comment]
> > @2easyjunmin <img alt="image" width="798" src="https://private-user-images.githubusercontent.com/39932550/389758151-f6fdabb4-1896-4310-9cc5-48a368b09d1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwMTYzNzMsIm5iZiI6MTczMzAxNjA3MywicGF0aCI6Ii8zOTkzMjU1MC8zODk3NTgxNTEtZjZmZGFiYjQtMTg5Ni00MzEwLTljYzUtNDhhMzY4YjA5ZDFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAxVDAxMjExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1ZWVhNDc3YTRhZjE4OTFjMjMzY2Q2ZjRlZDkwOTAyYTJmMjliM2NlOTUwODEzMDEyNDA0MDdiN2E1ZDA3NDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xQSdCwxKBHD0cnCZMMauTVGNmDZ2k_y207NgLtjWhvM"> This is my detection program, once every hour. Green represents correct.
> 
> Thank you so much for your amazing work! We truly appreciate your contributions. Would you consider setting up a Buy Me a Coffee profile so we can buy you some coffees as well? We’ve already supported gcui’s profile https://buymeacoffee.com/gcui and would love to do the same for you as a small token of our gratitude. ❤️

I can only add USDT as a sponsorship option.

**Comment by CalvinChenXYZ** [comment]
> > > @2easyjunmin <img alt="image" width="798" src="https://private-user-images.githubusercontent.com/39932550/389758151-f6fdabb4-1896-4310-9cc5-48a368b09d1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwMTYzNzMsIm5iZiI6MTczMzAxNjA3MywicGF0aCI6Ii8zOTkzMjU1MC8zODk3NTgxNTEtZjZmZGFiYjQtMTg5Ni00MzEwLTljYzUtNDhhMzY4YjA5ZDFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAxVDAxMjExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1ZWVhNDc3YTRhZjE4OTFjMjMzY2Q2ZjRlZDkwOTAyYTJmMjliM2NlOTUwODEzMDEyNDA0MDdiN2E1ZDA3NDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xQSdCwxKBHD0cnCZMMauTVGNmDZ2k_y207NgLtjWhvM"> This is my detection program, once every hour. Green represents correct.
> > 
> > 
> > Thank you so much for your amazing work! We truly appreciate your contributions. Would you consider setting up a Buy Me a Coffee profile so we can buy you some coffees as well? We’ve already supported gcui’s profile https://buymeacoffee.com/gcui and would love to do the same for you as a small token of our gratitude. ❤️
> 
> I can only add USDT as a sponsorship option.

Thank you for the updates. Unfortunately, our bank has forbidden us from engaging in any crypto-related transactions. We will make sure to keep an eye on your donation page and will donate once Buy Me a Coffee or Ko-fi options become available. Thanks again for your amazing work!
